/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelsystem.Gui;

import hotelsystem.Bill;
import hotelsystem.Booking;
import hotelsystem.BookingController;
import hotelsystem.BookingController;
import hotelsystem.Guest;
import hotelsystem.Room;
import hotelsystem.RoomType;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author dinam
 */
public class Bookingform extends javax.swing.JFrame {

    private BookingController controller = new BookingController(50);

    public Bookingform() {

        initComponents();
        // Center the form on screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        reservaion = new javax.swing.JLabel();
        updatebOOKING = new javax.swing.JButton();
        checkin = new javax.swing.JPanel();
        guestName = new javax.swing.JLabel();
        SelectRoom = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        Remarks = new javax.swing.JLabel();
        noOfGuests = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        roomType = new javax.swing.JComboBox<>();
        durationField = new javax.swing.JTextField();
        noOfGuestsField = new javax.swing.JTextField();
        remarksField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        checkout = new javax.swing.JLabel();
        checkoutField = new javax.swing.JSpinner();
        checkinField = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        AC = new javax.swing.JLabel();
        WIFI = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yesNoBox = new javax.swing.JComboBox<>();
        yesNoBox1 = new javax.swing.JComboBox<>();
        yesNoBox2 = new javax.swing.JComboBox<>();
        saveAndExit = new javax.swing.JButton();
        cancelBooking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        confirmBooking = new javax.swing.JButton();
        viewHistory = new javax.swing.JButton();
        backbttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        reservaion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reservaion.setForeground(new java.awt.Color(0, 0, 153));
        reservaion.setText("ROOM RESERVATION");

        updatebOOKING.setBackground(new java.awt.Color(255, 204, 0));
        updatebOOKING.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatebOOKING.setForeground(new java.awt.Color(255, 255, 255));
        updatebOOKING.setText("Update Booking");
        updatebOOKING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebOOKINGActionPerformed(evt);
            }
        });

        checkin.setBackground(new java.awt.Color(255, 255, 255));
        checkin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        checkin.setForeground(new java.awt.Color(153, 0, 0));

        guestName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guestName.setText("Guest Name:");

        SelectRoom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SelectRoom.setText("Select Room:");

        Duration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Duration.setText("Duration:");

        Remarks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Remarks.setText("Special Remarks:");

        noOfGuests.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noOfGuests.setText("Guests:");

        nameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        roomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELUXE", "SUITE", "SINGLE", "DOUBLE" }));
        roomType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        roomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeActionPerformed(evt);
            }
        });

        durationField.setText("\n");
        durationField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        noOfGuestsField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        noOfGuestsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfGuestsFieldActionPerformed(evt);
            }
        });

        remarksField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Check in Date:");

        checkout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkout.setText("Check Out Date:");

        checkoutField.setModel(new javax.swing.SpinnerDateModel());

        checkinField.setModel(new javax.swing.SpinnerDateModel());

        AC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AC.setText("Room AC:");

        WIFI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WIFI.setText("Room Wifi:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Room TV:");

        yesNoBox.setEditable(true);
        yesNoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        yesNoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesNoBoxActionPerformed(evt);
            }
        });

        yesNoBox1.setEditable(true);
        yesNoBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        yesNoBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesNoBox1ActionPerformed(evt);
            }
        });

        yesNoBox2.setEditable(true);
        yesNoBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        yesNoBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesNoBox2ActionPerformed(evt);
            }
        });

        saveAndExit.setBackground(new java.awt.Color(153, 0, 0));
        saveAndExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveAndExit.setForeground(new java.awt.Color(255, 255, 255));
        saveAndExit.setText("Save & Exit");
        saveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkinLayout = new javax.swing.GroupLayout(checkin);
        checkin.setLayout(checkinLayout);
        checkinLayout.setHorizontalGroup(
            checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkinLayout.createSequentialGroup()
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(checkinLayout.createSequentialGroup()
                                .addComponent(guestName, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, checkinLayout.createSequentialGroup()
                                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SelectRoom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Duration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noOfGuests, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(checkinLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkinLayout.createSequentialGroup()
                                .addComponent(checkinField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                .addComponent(Remarks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remarksField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(checkinLayout.createSequentialGroup()
                                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(noOfGuestsField)
                                    .addComponent(durationField)
                                    .addComponent(roomType, 0, 141, Short.MAX_VALUE)
                                    .addComponent(nameField))
                                .addGap(33, 33, 33)
                                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WIFI, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(checkinLayout.createSequentialGroup()
                                        .addComponent(yesNoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(checkinLayout.createSequentialGroup()
                                        .addComponent(yesNoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(checkinLayout.createSequentialGroup()
                                        .addComponent(yesNoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(checkinLayout.createSequentialGroup()
                        .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkoutField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveAndExit)
                .addContainerGap())
        );
        checkinLayout.setVerticalGroup(
            checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinLayout.createSequentialGroup()
                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkinLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(checkinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guestName)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AC)
                            .addComponent(yesNoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WIFI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesNoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectRoom))
                        .addGap(18, 18, 18)
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesNoBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Duration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noOfGuestsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noOfGuests))
                        .addGap(36, 36, 36)
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkinLayout.createSequentialGroup()
                                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(checkinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkinLayout.createSequentialGroup()
                                .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(remarksField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Remarks))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(checkinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkoutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkout))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveAndExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cancelBooking.setBackground(new java.awt.Color(0, 102, 255));
        cancelBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBooking.setForeground(new java.awt.Color(255, 255, 255));
        cancelBooking.setText("Cancel Booking");
        cancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Booking Details");

        confirmBooking.setBackground(new java.awt.Color(0, 153, 0));
        confirmBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmBooking.setForeground(new java.awt.Color(255, 255, 255));
        confirmBooking.setText("Confirm Booking");
        confirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBookingActionPerformed(evt);
            }
        });

        viewHistory.setBackground(new java.awt.Color(0, 0, 153));
        viewHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewHistory.setForeground(new java.awt.Color(255, 255, 255));
        viewHistory.setText("View History");
        viewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryActionPerformed(evt);
            }
        });

        backbttn.setBackground(new java.awt.Color(153, 0, 51));
        backbttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backbttn.setForeground(new java.awt.Color(255, 255, 255));
        backbttn.setText("Back");
        backbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(reservaion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(confirmBooking)
                                    .addGap(37, 37, 37)
                                    .addComponent(cancelBooking)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(updatebOOKING)
                                    .addGap(13, 13, 13)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(reservaion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(backbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebOOKING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebOOKINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebOOKINGActionPerformed
        try {
            // Prompt the user to enter the specific Booking ID to be modified
            String idInput = javax.swing.JOptionPane.showInputDialog(this,
                    "Please enter the Booking ID you want to update:",
                    "Update Booking",
                    javax.swing.JOptionPane.QUESTION_MESSAGE);
            if (idInput == null || idInput.trim().isEmpty()) {
                return;// Exit the method if the user cancels the input or leaves it empty
            }            // Convert the input strings to integers and retrieve data from the UI fields
            int id = Integer.parseInt(idInput.trim());
            int newDuration = Integer.parseInt(durationField.getText().trim());
            int newGuests = Integer.parseInt(noOfGuestsField.getText().trim());
            String newRemarks = remarksField.getText();

            // Get the selected room type from the ComboBox and convert it to a matching Enum constant
            String selectedTypeStr = roomType.getSelectedItem().toString().toUpperCase();
            RoomType type = RoomType.valueOf(selectedTypeStr);

            // Use the controller to find a room that matches the requested type
            Room newRoom = controller.findAvailableRoom(type);
// Execute the update via the controller with the new data
            controller.updateBooking(id, newDuration, newGuests, newRemarks, newRoom);

            // Display a success message to the user
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Booking #" + id + " has been updated successfully!",
                    "Update Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
// Update the status area with the details of the changes
            jTextArea1.setText("--- Action: Updated Booking #" + id + " ---\n");
            jTextArea1.append("New Duration: " + newDuration + " nights\n");
            jTextArea1.append("New Guests: " + newGuests + "\n");

        } catch (NumberFormatException e) {
            // Handle cases where non-numeric data is entered into numeric fields
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Input Error: Please make sure ID, Duration, and Guests are numbers only.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Display any other runtime errors in the text area for debugging
            jTextArea1.setText("Error during update: " + e.getMessage());
        };
    }//GEN-LAST:event_updatebOOKINGActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void roomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeActionPerformed

    private void noOfGuestsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfGuestsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfGuestsFieldActionPerformed

    private void yesNoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesNoBoxActionPerformed
        String status = yesNoBox.getSelectedItem().toString();
        jTextArea1.append("AC Preference changed to: " + status + "\n");
    }//GEN-LAST:event_yesNoBoxActionPerformed

    private void yesNoBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesNoBox1ActionPerformed
        // Get the selected item from the ComboBox (Yes/No) and convert it to a String
        String status = yesNoBox1.getSelectedItem().toString();
        // Add a new line to the JTextArea to log the change in AC preference
        jTextArea1.append("WiFi Preference changed to: " + status + "\n");
    }//GEN-LAST:event_yesNoBox1ActionPerformed

    private void yesNoBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesNoBox2ActionPerformed
        String status = yesNoBox2.getSelectedItem().toString();
        jTextArea1.append("TV Preference changed to: " + status + "\n");
    }//GEN-LAST:event_yesNoBox2ActionPerformed

    private void saveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndExitActionPerformed

        // Call the controller to write current data to the text file
        controller.saveBookingsToFile();

        // Log the status to the UI text area
        jTextArea1.append("Data saved. Closing application...\n");

        System.exit(0);
    }//GEN-LAST:event_saveAndExitActionPerformed

    private void cancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingActionPerformed
        try {

            // Display an input dialog to get the Booking ID from the user
            String inputID = javax.swing.JOptionPane.showInputDialog(this,
                    "Please enter the Booking ID to cancel:",
                    "Cancel Booking",
                    javax.swing.JOptionPane.QUESTION_MESSAGE);
            if (inputID != null && !inputID.trim().isEmpty()) {
                int id = Integer.parseInt(inputID.trim());

                // Ask the controller to cancel the booking and return the result (true/false)
                boolean isCancelled = controller.cancelBooking(id);

                if (isCancelled) {
                    // If cancellation was successful, show a confirmation message
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Booking ID " + id + " has been successfully cancelled and the room is now available.",
                            "Success",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Update the text area to reflect the last action
                    jTextArea1.setText("Action: Cancelled Booking #" + id);
                } else {
                    // If the controller couldn't find the ID, show an error message
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Booking ID not found. Please check the ID and try again.",
                            "Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Invalid ID format. Please enter a numeric ID.",
                    "Input Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            // Log any other unexpected errors to the text area
        } catch (Exception e) {
            jTextArea1.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cancelBookingActionPerformed

    private void confirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingActionPerformed

        try {
            // Set text color and validate that the guest name is not empty
            jTextArea1.setForeground(java.awt.Color.WHITE);
            String name = nameField.getText().trim();
            if (name.isEmpty()) {
                jTextArea1.setText("Error: Please enter a guest name.");
                return;
            }

            // Retrieve dates from JSpinners and convert them to LocalDate
            java.util.Date inSpinnerDate = (java.util.Date) checkinField.getValue();
            java.util.Date outSpinnerDate = (java.util.Date) checkoutField.getValue();

            java.time.LocalDate inDate = java.time.LocalDate.ofInstant(inSpinnerDate.toInstant(), java.time.ZoneId.systemDefault());
            java.time.LocalDate outDate = java.time.LocalDate.ofInstant(outSpinnerDate.toInstant(), java.time.ZoneId.systemDefault());

            int stayDuration = (int) java.time.temporal.ChronoUnit.DAYS.between(inDate, outDate);
// Ensure the stay duration is at least one night
            if (stayDuration <= 0) {
                jTextArea1.setText("Error: Check-out date must be at least 1 day after Check-in.");
                return;
            }
            // Determine room type and check for availability through the controller
            String selectedTypeStr = roomType.getSelectedItem().toString().toUpperCase();
            RoomType selectedType = RoomType.valueOf(selectedTypeStr);
            Room selectedRoom = controller.findAvailableRoom(selectedType);

            if (selectedRoom == null) {
                jTextArea1.setText("No " + selectedType + " rooms available.");
                return;
            }
            // Get guest count and extra preferences (AC, Wifi, TV)
            int guestsCount = Integer.parseInt(noOfGuestsField.getText().trim());
            boolean needsAC = yesNoBox.getSelectedItem().toString().equalsIgnoreCase("Yes");
            boolean needsWifi = yesNoBox1.getSelectedItem().toString().equalsIgnoreCase("Yes");
            boolean needsTV = yesNoBox2.getSelectedItem().toString().equalsIgnoreCase("Yes");

            String finalRemarks = remarksField.getText()
                    + " [Extras: AC=" + needsAC
                    + ", Wifi=" + needsWifi
                    + ", TV=" + needsTV + "]";
            Guest currentGuest = new Guest(name, "email@example.com", "012345678", "pass1234567", 101, 2);
            Booking newBooking = controller.bookRoom(currentGuest, selectedRoom, stayDuration,
                    guestsCount, finalRemarks, inDate, outDate);

            if (newBooking != null) {
                // Display booking summary in the text area
                jTextArea1.setText("--- Booking Details Saved ---\n");
                jTextArea1.append("ID: " + newBooking.getBookingID() + "\n");
                jTextArea1.append("Guest Name: " + name + "\n");
                jTextArea1.append("Room Number: " + selectedRoom.getRoomNumber() + "\n");
                jTextArea1.append("Room Type: " + selectedTypeStr + "\n");
                jTextArea1.append("Duration: " + stayDuration + " nights\n");
                jTextArea1.append("\nNote: Total price will be calculated in the payment page.");

                // Ask the user if they want to proceed to the payment screen
                int response = javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "Booking saved! Go to Payment page to see total price?",
                        "Proceed to Payment",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE
                );

                if (response == javax.swing.JOptionPane.YES_OPTION) {
                    Bill newBill = null;

                    // Open the Payment GUI and pass the booking data
                    BillGUI paymentPage = new BillGUI(newBooking);
                    paymentPage.setVisible(true);
                    this.dispose();// Close the current booking window
                    
                    
                    
                }
            }

        } catch (NumberFormatException e) {
            jTextArea1.setText("Error: Please enter a valid number for guests.");
        } catch (Exception e) {
            jTextArea1.setText("Error: " + e.getMessage());
        }
        controller.saveBookingsToFile();

        jTextArea1.append("Booking confirmed and saved to file!\n");
    }//GEN-LAST:event_confirmBookingActionPerformed

    private void viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryActionPerformed
        // Retrieve the name from the input field and remove extra whitespace
        String searchName = nameField.getText().trim();
        if (searchName.isEmpty()) {
            // Validate that the name field is not empty
            jTextArea1.setText("Enter a Guest Name to view history.");
            return;
        }
        Guest searchGuest = new Guest();
        searchGuest.setUserName(searchName);
// Request the list of bookings associated with this guest from the controller
        ArrayList<Booking> history = controller.viewBookings(searchGuest);

        jTextArea1.setText("--- History for " + searchName + " ---\n");
        if (history.isEmpty()) {
            // Check if the history list contains any records
            jTextArea1.append("No bookings found.");
        } else {
            // Iterate through each booking record and append details to the text area
            for (Booking b : history) {
                jTextArea1.append("ID: " + b.getBookingID() + " | Room: " + b.getRoom().getRoomNumber()
                        + " | Total: $" + b.getTotalPrice() + "\n");
            }
        }
    }//GEN-LAST:event_viewHistoryActionPerformed

    private void backbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbttnActionPerformed
        // Display a confirmation dialog to prevent accidental navigation
        int choice = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to go back to the Hotel Page?",
                "Confirmation",
                javax.swing.JOptionPane.YES_NO_OPTION);
// Check if the user clicked the 'Yes' button
        if (choice == javax.swing.JOptionPane.YES_OPTION) {

            try {
                HotellGUI hotel = new HotellGUI(); 
                hotel.setVisible(true);

                this.dispose();

            } catch (Exception e) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_backbttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookingform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AC;
    private javax.swing.JLabel Duration;
    private javax.swing.JLabel Remarks;
    private javax.swing.JLabel SelectRoom;
    private javax.swing.JLabel WIFI;
    private javax.swing.JButton backbttn;
    private javax.swing.JButton cancelBooking;
    private javax.swing.JPanel checkin;
    private javax.swing.JSpinner checkinField;
    private javax.swing.JLabel checkout;
    private javax.swing.JSpinner checkoutField;
    private javax.swing.JButton confirmBooking;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel guestName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel noOfGuests;
    private javax.swing.JTextField noOfGuestsField;
    private javax.swing.JTextField remarksField;
    private javax.swing.JLabel reservaion;
    private javax.swing.JComboBox<String> roomType;
    private javax.swing.JButton saveAndExit;
    private javax.swing.JButton updatebOOKING;
    private javax.swing.JButton viewHistory;
    private javax.swing.JComboBox<String> yesNoBox;
    private javax.swing.JComboBox<String> yesNoBox1;
    private javax.swing.JComboBox<String> yesNoBox2;
    // End of variables declaration//GEN-END:variables
}
