/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelsystem.Gui;

import hotelsystem.CurrentUserHolder;
import hotelsystem.CurrentUserHolder;
import hotelsystem.Gui.Bookingform;
import hotelsystem.Gui.LoginForm;
import hotelsystem.RoomType;
import hotelsystem.RoomType;
import hotelsystem.User;
import hotelsystem.User;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haneen
 */
public class HotellGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HotellGUI.class.getName());
    private DefaultTableModel model;

    // Define the possible user types in the system
    public enum UserRole {
        ADMIN, EMPLOYEE, GUEST
    }

    private User currentUser;
    private UserRole currentUserRole;

    /**
     * Creates new form HotellGUI Changed to Default Constructor to fix Login
     * errors and use Session management
     */
    public HotellGUI() {
        initComponents();

        // Retrieve the current logged-in user from the Global Holder
        this.currentUser = CurrentUserHolder.getUser();

        // Determine the Role based on the User object data
        if (currentUser != null) {
            try {
                // Convert role string (e.g., "Admin") to the matching Enum constant
                this.currentUserRole = UserRole.valueOf(currentUser.getRole().toUpperCase());
            } catch (Exception e) {
                // Fallback to Guest if role is unrecognized
                this.currentUserRole = UserRole.GUEST;
            }
        } else {
            // Default to Guest if no user session is found
            this.currentUserRole = UserRole.GUEST;
        }

        // Initialize table and apply UI restrictions based on role
        model = (DefaultTableModel) showroomsTable.getModel();
        model.setRowCount(0);
        applyPermissions();

        // Center the window on the screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method controls the visibility of UI components (buttons/panels)
     * based on the user's permissions.
     */
    private void applyPermissions() {
        if (currentUserRole == null) {
            return;
        }

        switch (currentUserRole) {
            case ADMIN:
                // Admins have full access; no components are hidden
                 EmployeeSide.setVisible(true);
                
                 
                break;

            case EMPLOYEE:
                // Employees are restricted from modifying the room catalog
                EmployeeSide.setVisible(true);
                AddRoom.setVisible(true);
                DeleteRoom.setVisible(true);
           
           
                break;

            case GUEST:
                // Guests have read-only access to rooms and cannot see management tools
                mngRoom.setVisible(false);
                AddRoom.setVisible(false);
                DeleteRoom.setVisible(false);
                EditRoom.setVisible(false);

         
                
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mngRoom = new javax.swing.JButton();
        addBooking = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        profilebutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        EmployeeSide = new javax.swing.JPanel();
        Booking = new javax.swing.JPanel();
        ClientName = new javax.swing.JTextField();
        roomNo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        ConfirmBook = new javax.swing.JButton();
        CancelBooking = new javax.swing.JButton();
        EditBooking = new javax.swing.JButton();
        AvaliableRooms = new javax.swing.JPanel();
        AddRoom = new javax.swing.JButton();
        DeleteRoom = new javax.swing.JButton();
        EditRoom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showroomsTable = new javax.swing.JTable();
        AvailableroomsLabel = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Grand Plaza Hotel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        mngRoom.setText("Manage Rooms");
        mngRoom.addActionListener(this::mngRoomActionPerformed);

        addBooking.setText("Bookings");
        addBooking.addActionListener(this::addBookingActionPerformed);

        logOut.setForeground(new java.awt.Color(255, 0, 51));
        logOut.setText("Log Out");
        logOut.addActionListener(this::logOutActionPerformed);

        profilebutton.setText("Profile");
        profilebutton.addActionListener(this::profilebuttonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mngRoom)
                    .addComponent(addBooking)
                    .addComponent(profilebutton)
                    .addComponent(logOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mngRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOut)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.CardLayout());

        Booking.setPreferredSize(new java.awt.Dimension(600, 481));

        ClientName.addActionListener(this::ClientNameActionPerformed);

        roomNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115" }));
        roomNo.addActionListener(this::roomNoActionPerformed);

        empTable.setBackground(new java.awt.Color(204, 204, 204));
        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "BookingID", "Client Name", "Room No", "CheckIn date", "CheckOut date", "status"
            }
        ));
        jScrollPane2.setViewportView(empTable);

        ConfirmBook.setBackground(new java.awt.Color(51, 204, 0));
        ConfirmBook.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmBook.setText("Confirm Booking");
        ConfirmBook.addActionListener(this::ConfirmBookActionPerformed);

        CancelBooking.setBackground(new java.awt.Color(255, 51, 0));
        CancelBooking.setForeground(new java.awt.Color(255, 255, 255));
        CancelBooking.setText("Cancel Booking");
        CancelBooking.addActionListener(this::CancelBookingActionPerformed);

        EditBooking.setBackground(new java.awt.Color(0, 153, 255));
        EditBooking.setForeground(new java.awt.Color(255, 255, 255));
        EditBooking.setText("Edit Booking");
        EditBooking.addActionListener(this::EditBookingActionPerformed);

        javax.swing.GroupLayout BookingLayout = new javax.swing.GroupLayout(Booking);
        Booking.setLayout(BookingLayout);
        BookingLayout.setHorizontalGroup(
            BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingLayout.createSequentialGroup()
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingLayout.createSequentialGroup()
                                .addComponent(ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(roomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BookingLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ConfirmBook, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BookingLayout.setVerticalGroup(
            BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(BookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmBook)
                    .addComponent(EditBooking)
                    .addComponent(CancelBooking))
                .addContainerGap())
        );

        AddRoom.setBackground(new java.awt.Color(102, 204, 0));
        AddRoom.setForeground(new java.awt.Color(255, 255, 255));
        AddRoom.setText("Add Room");

        DeleteRoom.setBackground(new java.awt.Color(255, 51, 0));
        DeleteRoom.setForeground(new java.awt.Color(255, 255, 255));
        DeleteRoom.setText("Delete Room");

        EditRoom.setBackground(new java.awt.Color(51, 102, 255));
        EditRoom.setForeground(new java.awt.Color(255, 255, 255));
        EditRoom.setText("Edit Room");

        showroomsTable.setBackground(new java.awt.Color(204, 204, 204));
        showroomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room No.", "Room Type", "Price Per Night", "Status"
            }
        ));
        jScrollPane1.setViewportView(showroomsTable);

        AvailableroomsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AvailableroomsLabel.setText("Avaliable Rooms");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout AvaliableRoomsLayout = new javax.swing.GroupLayout(AvaliableRooms);
        AvaliableRooms.setLayout(AvaliableRoomsLayout);
        AvaliableRoomsLayout.setHorizontalGroup(
            AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvaliableRoomsLayout.createSequentialGroup()
                .addGroup(AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AvaliableRoomsLayout.createSequentialGroup()
                        .addGroup(AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvaliableRoomsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AvaliableRoomsLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(AddRoom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(DeleteRoom)
                                .addGap(72, 72, 72)
                                .addComponent(EditRoom)
                                .addGap(14, 14, 14)))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvaliableRoomsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AvailableroomsLabel)
                        .addGap(226, 226, 226)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvaliableRoomsLayout.createSequentialGroup()
                    .addContainerGap(54, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
        AvaliableRoomsLayout.setVerticalGroup(
            AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvaliableRoomsLayout.createSequentialGroup()
                .addGroup(AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AvaliableRoomsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(AvaliableRoomsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AvailableroomsLabel)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddRoom)
                            .addComponent(DeleteRoom)
                            .addComponent(EditRoom))))
                .addGap(18, 18, 18))
            .addGroup(AvaliableRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvaliableRoomsLayout.createSequentialGroup()
                    .addContainerGap(63, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout EmployeeSideLayout = new javax.swing.GroupLayout(EmployeeSide);
        EmployeeSide.setLayout(EmployeeSideLayout);
        EmployeeSideLayout.setHorizontalGroup(
            EmployeeSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeSideLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(AvaliableRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        EmployeeSideLayout.setVerticalGroup(
            EmployeeSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeSideLayout.createSequentialGroup()
                .addGroup(EmployeeSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeSideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AvaliableRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmployeeSideLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGap(13203, 13203, 13203))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmployeeSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeSide, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mngRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngRoomActionPerformed
        RoomGUI roomPage = new RoomGUI(); 
        roomPage.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_mngRoomActionPerformed
// Logic for confirming a new room booking
    private void ConfirmBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBookActionPerformed
        String name = ClientName.getText().trim();

        // Check if the name contains only letters and spaces (no numbers allowed)
        if (!name.matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(this, "Invalid Name! Please use letters only (no numbers).");
            return;
        }

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Client Name!");
            return;
        }
        String room = roomNo.getSelectedItem().toString();
        try {
            // Get the table model to manipulate data
            model = (DefaultTableModel) empTable.getModel();

            // Add a new row with booking details: [ID, Name, Room, Dates, Status]
            model.addRow(new Object[]{
                model.getRowCount() + 1,
                name,
                room,
                "22-04-2026",
                "25-04-2026",
                "Confirmed"
            });

            // Notify the user that the operation was successful
            JOptionPane.showMessageDialog(this, "Booking confirmed for " + name);

            // Clear input fields for the next booking
            ClientName.setText("");
            roomNo.setSelectedIndex(0);

        } catch (Exception e) {
            // Catch any unexpected errors and display them to the user
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_ConfirmBookActionPerformed
// Logic to add a new room to the table via input dialogs
     // Initialize variables with default values to satisfy the compiler
     int roomNum = 0;
     RoomType type = RoomType.SINGLE;
     double price = 0.0;

//Logic to update existing room details in the table
    private void ClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientNameActionPerformed

    }//GEN-LAST:event_ClientNameActionPerformed

    private void roomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNoActionPerformed
// Logic to update an existing booking in the table
    private void EditBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookingActionPerformed
        model = (DefaultTableModel) empTable.getModel();

        int selectedRowIndex = empTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            // Retrieve new values from input fields
            String updatedName = ClientName.getText().trim();
            String updatedRoom = roomNo.getSelectedItem().toString();
// Update the table cells with new data
            model.setValueAt(updatedName, selectedRowIndex, 1);
            model.setValueAt(updatedRoom, selectedRowIndex, 2);

            JOptionPane.showMessageDialog(this, "Booking Updated Successfully!");
            // Reset fields after editing
            ClientName.setText("");
            roomNo.setSelectedIndex(0);

        } else {

            JOptionPane.showMessageDialog(this, "Please select a row from the table to edit!");
        }
    }//GEN-LAST:event_EditBookingActionPerformed
// Logic to delete/cancel a booking with confirmation
    private void CancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingActionPerformed
        model = (DefaultTableModel) empTable.getModel();

        int selectedRowIndex = empTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            // Ask for user confirmation before deleting
            int dialogResult = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to cancel this booking?",
                    "Warning",
                    JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {

                model.removeRow(selectedRowIndex);

                JOptionPane.showMessageDialog(this, "Booking Cancelled Successfully!");
                ClientName.setText("");
                roomNo.setSelectedIndex(0);
            }

        } else {

            JOptionPane.showMessageDialog(this, "Please select a booking from the table to cancel!");
        }

    }//GEN-LAST:event_CancelBookingActionPerformed

    private void addBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingActionPerformed
        Bookingform bookingPage = new Bookingform();
        bookingPage.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_addBookingActionPerformed
// Navigation: Logout and return to Login Screen
    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        CurrentUserHolder.setUser(null); // Clear session data
        new LoginForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_logOutActionPerformed

    private void profilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebuttonActionPerformed
        if (currentUser != null) {
            new UserProfileForm().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_profilebuttonActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
         /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
          */
         try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
                 }
             }
         } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
             logger.log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>

         java.awt.EventQueue.invokeLater(() -> {
             new HotellGUI().setVisible(true);
         });
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoom;
    private javax.swing.JLabel AvailableroomsLabel;
    private javax.swing.JPanel AvaliableRooms;
    private javax.swing.JPanel Booking;
    private javax.swing.JButton CancelBooking;
    private javax.swing.JTextField ClientName;
    private javax.swing.JButton ConfirmBook;
    private javax.swing.JButton DeleteRoom;
    private javax.swing.JButton EditBooking;
    private javax.swing.JButton EditRoom;
    private javax.swing.JPanel EmployeeSide;
    private javax.swing.JButton addBooking;
    private javax.swing.JTable empTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton mngRoom;
    private javax.swing.JButton profilebutton;
    private javax.swing.JComboBox<String> roomNo;
    private javax.swing.JTable showroomsTable;
    // End of variables declaration//GEN-END:variables
}
