/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelsystem.Gui;

import hotelsystem.CurrentUserHolder;
import hotelsystem.User;
import hotelsystem.UserFileManager;

/**
 *
 * @author daliaelbarbary
 */
public class LoginForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        btnSignUP = new javax.swing.JButton();
        MyProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(390, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 330, 50));

        Password.addActionListener(this::PasswordActionPerformed);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 330, 50));

        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        login_button.setBackground(new java.awt.Color(186, 225, 255));
        login_button.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        login_button.setText("Log In");
        login_button.addActionListener(this::login_buttonActionPerformed);
        getContentPane().add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 40));

        btnSignUP.setBackground(new java.awt.Color(168, 230, 207));
        btnSignUP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSignUP.setText("Sign Up");
        btnSignUP.addActionListener(this::btnSignUPActionPerformed);
        getContentPane().add(btnSignUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 40));

        MyProfile.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        MyProfile.setText("Log In");
        getContentPane().add(MyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String email = txtEmail.getText();
        String password = new String(Password.getPassword());

        // Search for the user in the loaded list
        User foundUser = null;
        for (User u : User.allUsers) {
            if (u.getUserEmail().equalsIgnoreCase(email) && u.getUserPassword().equals(password)) {
                foundUser = u;
                break;
            }
        }

        if (foundUser != null) {
            // SAVE the found user (Admin, Employee, or Guest) in our global holder
            CurrentUserHolder.setUser(foundUser);

            // Open the main GUI (it will now automatically know who the user is)
            new HotellGUI().setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid credentials!");
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void btnSignUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUPActionPerformed

        //Create an instance of the specific frame class
        CreateAccountForm createAccountFrame = new CreateAccountForm();

        //Center the window on the screen
        createAccountFrame.setLocationRelativeTo(null);

        //Display the registration form
        createAccountFrame.setVisible(true);

        //Close the Login form so it's not cluttering the desktop
        this.dispose();

    }//GEN-LAST:event_btnSignUPActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //Load all users from the text file into User.allUsers list
        UserFileManager.loadUsersData();

        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MyProfile;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btnSignUP;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
